name: ekadashi_calendar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  http: ^1.6.0
  intl: ^0.20.0
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.2
  flutter_timezone: ^3.0.0
  shared_preferences: ^2.5.4
  geocoding: ^4.0.0
  table_calendar: ^3.2.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  # ADDED: explicitly include the app icon here so rootBundle.load() can find it
  assets:
    - assets/ekadashi_data_en.json
    - assets/ekadashi_data_ta.json
    - assets/ekadashi_data_hi.json
    - assets/app_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#00A19B"
  adaptive_icon_foreground: "assets/app_icon.png"
  notification_icon: "notification_icon"

flutter_native_splash:
  color: "#121212"
  image: "assets/app_icon.png"
  color_dark: "#121212"
  image_dark: "assets/app_icon.png"
  android_12:
    image: "assets/app_icon.png"
    icon_background_color: "#121212"
    icon_background_color_dark: "#121212"