name: ekadashi_calendar
description: "Ekadashi Calendar App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.2.2

  # Core
  intl: ^0.20.0
  shared_preferences: ^2.5.4
  provider: ^6.1.1

  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Notifications
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.2
  flutter_timezone: ^3.0.0

  # UI
  table_calendar: ^3.2.0

  # Settings
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/ekadashi_data_en.json
    - assets/ekadashi_data_ta.json
    - assets/ekadashi_data_hi.json
    - assets/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#00A19B"
  adaptive_icon_foreground: "assets/icon/app_icon.png"